# Basic Information 
title: Jiawei Mo
position: Applied Scientist
affiliation: Amazon AGI
affiliation_link: https://www.amazon.science/
email: jiawei0573@gmail.com

keywords: jiawei mo, slam, sensor fusion, nerf, generative AI for 3D and videos
description: Personal website of Jiawei Mo.
canonical: https://https://jiawei-mo.github.io/

google_scholar: https://scholar.google.com/citations?user=ROBeZmgAAAAJ&hl
cv_link: assets/files/Resume.pdf
linkedin: https://www.linkedin.com/in/jiawei-mo/

avatar: ./assets/img/avatar.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

auto_dark_mode: true
font: "Serif" # or "Sans Serif"
google_analytics: UA-111540567-4
