# Basic Information 
title: Jiawei Mo
position: Applied Scientist
affiliation: Amazon
affiliation_link: https://aws.amazon.com/
email: jiawei0573@gmail.com

keywords: jiawei mo, slam, sensor fusion
description: Personal website of Jiawei Mo.
canonical: https://https://jiawei-mo.github.io/

google_scholar: https://scholar.google.com/citations?user=v-DwZWMAAAAJ&hl=en
cv_link: assets/files/Resume.pdf
linkedin: https://www.linkedin.com/in/jiawei-mo/

avatar: ./assets/img/avatar.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

enable_footnote: false
auto_dark_mode: true
font: "Serif" # or "Sans Serif"
google_analytics: UA-111540567-4
remote_theme: yaoyao-liu/minimal-light
